---
- import_tasks: archlinux.yml
  when: ansible_facts["os_family"] | lower == "archlinux"

- name: Ensure ~/.config/rofi exists
  file:
    state: directory
    path: "{{ lookup('env', 'HOME') }}/.config/rofi"

- name: Ensure ~/.config/rofi/config is up-to-date
  copy:
    src: config
    dest: "{{ lookup('env', 'HOME') }}/.config/rofi/config"