---
- import_tasks: archlinux.yml
  when: ansible_facts["os_family"] | lower == "archlinux"

- name: Ensure Tilix DConf settings are up-to-date
  dconf:
    key: /com/gexperts/Tilix/
    src: com.gexperts.Tilix.dconf

- name: Ensure ~/.config/tilix/schemes exists
  file:
    state: directory
    path: "{{ lookup('env', 'HOME') }}/.config/tilix/schemes"

- name: Ensure Hybrid color scheme is up-to-date
  get_url:
    url: https://raw.githubusercontent.com/storm119/Tilix-Themes/master/Themes/hybrid.json
    dest: "{{ lookup('env', 'HOME') }}/.config/tilix/schemes/hybrid.json"
