---
- import_tasks: archlinux.yml
  when: ansible_facts["os_family"] | lower == "archlinux"

- name: Ensure Tilix DConf settings are up-to-date
  dconf:
    key: /com/gexperts/Tilix/
    content: |
      [/]
      quake-specific-monitor=0
      sidebar-on-right=true
      use-tabs=false
      window-style='disable-csd-hide-toolbar'

      [keybindings]
      terminal-find='disabled'
      terminal-find-next='disabled'
      terminal-find-previous='disabled'

      [profiles/2b7c4080-0ddd-46c5-8f23-563fd3ba789d]
      background-color='#161719'
      badge-color-set=false
      bold-color-set=false
      cursor-colors-set=false
      foreground-color='#B7BCBA'
      highlight-colors-set=false
      login-shell=true
      palette=['#2A2E33', '#B84D51', '#B3BF5A', '#E4B55E', '#6E90B0', '#A17EAC', '#7FBFB4', '#B5B9B6', '#1D1F22', '#8D2E32', '#798431', '#E58A50', '#4B6B88', '#6E5079', '#4D7B74', '#5A626A']
      use-theme-colors=false
      visible-name='Default'

- name: Ensure ~/.config/tilix/schemes exists
  file:
    state: directory
    path: "{{ lookup('env', 'HOME') }}/.config/tilix/schemes"

- name: Ensure Hybrid color scheme is up-to-date
  get_url:
    url: https://raw.githubusercontent.com/storm119/Tilix-Themes/master/Themes/hybrid.json
    dest: "{{ lookup('env', 'HOME') }}/.config/tilix/schemes/hybrid.json"
