language: generic

script:
  - bin/install -b "$TRAVIS_BRANCH" && bin/check

matrix:
  include:
    - os: osx
      osx_image: xcode9.2
    - os: osx
      osx_image: xcode9.3
    - os: osx
      osx_image: xcode9.4.1
    - os: osx
      osx_image: xcode10.0
    - os: osx
      osx_image: xcode10.1
    - name: Check linters
      language: python
      python: 3.6.7
      install:
        - pip install -r requirements.txt
      script:
        - shellcheck -Calways bin/check bin/install bin/provision docker/bin/test
        - vint -c .vim/
