language: generic
os: osx

script:
  - bin/install -b "$TRAVIS_BRANCH"
  - bin/check

matrix:
  include:
    - osx_image: xcode9.2
    - osx_image: xcode9.3
    - osx_image: xcode9.4.1
    - osx_image: xcode10.0
    - osx_image: xcode10.1
