#!/usr/bin/env bash
#
#

source "${UNIXCONFDIR}/bash/aliases";

# source bashrc
source "${UNIXCONFDIR}/bashrc";

# allows bashrc to call bashprofile in case it wasn't already loaded
# note that exporting allows scripts not to load this (the calling
# shell already defined it)
export PROFILE_LOADED=1;