---
- import_tasks: archlinux.yml
  when: ansible_facts["os_family"] | lower == "archlinux"

- name: Ensure ~/.config/systemd/user exists
  file:
    state: directory
    path: "{{ lookup('env', 'HOME') }}/.config/systemd/user"

- name: Ensure ~/.config/systemd/user/xscreensaver.service is up-to-date
  copy:
    src: xscreensaver.service
    dest: "{{ lookup('env', 'HOME') }}/.config/systemd/user/xscreensaver.service"
  register: xscreensaver_systemd_unit

- name: Reload SystemD daemon (if needed)
  systemd:
    daemon_reload: yes
    name: xscreensaver
    state: restarted
    scope: user
  when: xscreensaver_systemd_unit.changed

- name: Ensure XScreensaver user service is enabled
  systemd:
    name: xscreensaver
    enabled: yes
    scope: user