---
- name: Ensure requirements for asdf-vm are installed (Debian)
  become: yes
  apt:
    name:
    - curl
    - git
  when: ansible_facts["os_family"] | lower == "debian"

- name: Checkout asdf-vm
  git:
    dest: "{{ lookup('env', 'HOME') }}/.asdf"
    repo: https://github.com/asdf-vm/asdf.git
    version: v0.9.0
  when: ansible_facts["system"] | lower == "linux"