---
- import_tasks: archlinux.yml
  when: ansible_facts["os_family"] | lower == "archlinux"

- name: Ensure Awesome user config is up-to-date
  copy:
    src: rc.lua
    dest: "{{ lookup('env', 'HOME') }}/.config/awesome/rc.lua"
  register: awesome_user_config

- debug:
    msg: "Awesome config changed, you have to restart it manually in order to see the changes."
  when: awesome_user_config.changed
