---
- import_tasks: archlinux.yml
  when: ansible_facts["os_family"] | lower == "archlinux"

- name: Ensure ~/.ssh exists
  file:
    state: directory
    path: "{{ lookup('env', 'HOME') }}/.ssh"

- name: Ensure user has an SSH key
  openssh_keypair:
    path: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"