---
- name: Ensure current user has an SSH key
  user:
    name: "{{ ansible_user_id }}"
    generate_ssh_key: yes
    ssh_key_type: ed25519

- name: Ensure SSH config is up-to-date
  copy:
    src: ./config
    dest: "{{ lookup('env', 'HOME') }}/.ssh/config"
