---
- name: Check if Yay is already installed
  shell: command -v yay
  changed_when: false
  register: yay_check

- name: Create temporary directory to build Yay
  tempfile:
    state: directory
    suffix: yay_build
  register: yay_tmp_dir
  when: yay_check.rc != 0

- name: Clone Yay from AUR
  git:
    repo: https://aur.archlinux.org/yay.git
    dest: "{{ yay_tmp_dir.path }}/yay"
    version: master
  when: yay_check.rc != 0

- name: Build and install Yay package
  command: makepkg -cis --noconfirm
  when: yay_check.rc != 0

- name: Cleanup temporary directory
  file:
    state: absent
    path: "{{ yay_tmp_dir.path }}"
  when: yay_check.rc != 0

- name: Ensure ~/.config/yay exists
  file:
    state: directory
    path: "{{ lookup('env', 'HOME') }}/.config/yay"

- name: Ensure ~/.config/yay/config.json is up-to-date
  copy:
    src: "config.json"
    dest: "{{ lookup('env', 'HOME') }}/.config/yay/config.json"