---
- name: Ensure TMUX is installed (ArchLinux)
  become: yes
  pacman:
    name: tmux
  when: ansible_facts["os_family"] | lower == "archlinux"

- name: Ensure TMUX is installed (Debian)
  become: yes
  apt:
    name: tmux
  when: ansible_facts["os_family"] | lower == "debian"

- name: Ensure ~/.tmux/plugins exists
  file:
    state: directory
    path: "{{ lookup('env', 'HOME') }}/.tmux/plugins"

- name: Ensure TMUX Plugin Manager is up-to-date
  git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "{{ lookup('env', 'HOME') }}/.tmux/plugins/tpm"
    version: master
  notify:
    - Source TMUX config

- name: Ensure TMUX config is up-to-date
  copy:
    src: "tmux.conf"
    dest: "{{ lookup('env', 'HOME') }}/.tmux.conf"
  notify:
    - Source TMUX config
