---
- import_tasks: archlinux.yml
  when: ansible_facts["os_family"] | lower == "archlinux"

- name: Ensure ~/.tmux/plugins exists
  file:
    state: directory
    path: "{{ lookup('env', 'HOME') }}/.tmux/plugins"

- name: Ensure TMUX Plugin Manager is up-to-date
  git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "{{ lookup('env', 'HOME') }}/.tmux/plugins/tpm"
    version: master

- name: Ensure ~/.config/tmux exists
  file:
    state: directory
    path: "{{ lookup('env', 'HOME') }}/.config/tmux"

- name: Ensure TMUX config is up-to-date
  copy:
    src: "tmux.conf"
    dest: "{{ lookup('env', 'HOME') }}/.config/tmux/tmux.conf"