---
- name: Ensure TMUX is installed
  homebrew:
    name: tmux

- name: Ensure ~/.config/tmux/plugins exists
  file:
    state: directory
    path: "{{ lookup('env', 'HOME') }}/.config/tmux/plugins"

- name: Ensure TMUX Plugin Manager is up-to-date
  git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "{{ lookup('env', 'HOME') }}/.config/tmux/plugins/tpm"
    version: master
  notify:
    - Source TMUX config

- name: Ensure TMUX config is up-to-date
  copy:
    src: "tmux.conf"
    dest: "{{ lookup('env', 'HOME') }}/.config/tmux/tmux.conf"
  notify:
    - Source TMUX config
