---
- import_tasks: archlinux.yml
  when: ansible_facts["os_family"] | lower == "archlinux"

- name: Ensure SystemD reloads daemons
  become: yes
  systemd:
    daemon_reload: yes
  when: cups_installation.changed

- name: Ensure CUPS socket is active
  become: yes
  systemd:
    name: org.cups.cupsd.socket
    state: started
    enabled: yes
