---
- import_tasks: archlinux.yml
  when: ansible_facts["os_family"] | lower == "archlinux"

- name: Ensure SystemD reloads daemons
  become: yes
  systemd:
    daemon_reload: yes
  when: bluez_installation.changed

- name: Ensure bluetooth service is started and enabled
  become: yes
  systemd:
    name: bluetooth.service
    state: started
    enabled: yes
