---
- import_tasks: archlinux.yml
  when: ansible_facts["os_family"] | lower == "archlinux"

- name: Ensure SystemD reloads daemons
  become: yes
  systemd:
    daemon_reload: yes
  when: avahi_installation.changed

- name: Ensure Avahi daemon service is started and enabled
  become: yes
  systemd:
    name: avahi-daemon.service
    state: started
    enabled: yes
