---
- name: Ensure Git config directory exists
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/git"
    state: directory

- name: Ensure Git config is up-to-date
  copy:
    src: ./
    dest: "{{ lookup('env', 'HOME') }}/.config/git/"
