---
- hosts: localhost
  become: yes
  vars:
    apt_file_path: /etc/apt/sources.list.d/grub-customizer.list
  tasks:
    - name: Ensure Grub Customizer APT repository is present
      apt_repository:
        repo: ppa:danielrichter2007/grub-customizer
      register: apt_repository
    - name: Ensure Grub Customizer package is present
      apt:
        name: grub-customizer
        update_cache: yes



