---
- name: Ensure Vim is installed
  homebrew:
    name: vim

- name: Ensure ~/.vim exists
  file:
    state: directory
    path: "{{ lookup('env', 'HOME') }}/.vim"

- name: Ensure .vimrc is up-to-date
  copy:
    src: ".vimrc"
    dest: "{{ lookup('env', 'HOME') }}/.vimrc"

- name: Ensure required directories exist
  file:
    state: directory
    path: "{{ lookup('env', 'HOME') }}/.vim/{{ item }}"
  with_items:
    - autoload
    - colors
    - ftplugin
    - plugin

- name: Ensure all sub-configs are up-to-date
  copy:
    src: ".vim/{{ item }}/"
    dest: "{{ lookup('env', 'HOME') }}/.vim/{{ item }}"
  with_items:
    - colors
    - ftplugin
    - plugin

- name: Ensure vim-plug is installed
  get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: "{{ lookup('env', 'HOME') }}/.vim/autoload/plug.vim"

- name: Ensure vim-plug and all plugins are up-to-date
  command: vim +PlugUpgrade +PlugInstall +PlugUpdate +qall
