---
- name: Ensure Docker is installed
  become: yes
  pacman:
    name:
      - docker
  register: docker_installation

- name: Ensure Docker Compose is installed
  become: yes
  pacman:
    name:
      - docker-compose
