---
- import_tasks: archlinux.yml
  when: ansible_facts["os_family"] | lower == "archlinux"

- name: Ensure Docker service is enabled and started
  become: yes
  systemd:
    name: docker.service
    state: started
    enabled: yes
    daemon_reload: "{{ docker_installation.changed }}"

- name: "Ensure {{ ansible_user_id }} is in the docker group"
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    groups:
      - docker
    append: yes

- name: Change storage driver to overlay2
  become: yes
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
  register: docker_daemon_json

- name: Restart Docker if daemon.json changed
  become: yes
  systemd:
    name: docker.service
    state: restarted
  when: docker_daemon_json.changed
