---
- hosts: localhost
  tasks:
    - name: Ensure current user has an SSH key
      user:
        name: "{{ ansible_user_id }}"
        generate_ssh_key: yes
        ssh_key_type: ed25519

    - name: Ensure Homebrew is up-to-date
      homebrew:
        update_homebrew: yes
        upgrade_all: yes
      when: not lookup("env", "CI")

    - name: Ensure Homebrew packages are installed
      homebrew:
        name:
          - ansible
          - bash
          - bat
          - fish
          - git
          - gnupg
          - mise
          - tmux
          - vim
          - zsh

- hosts: localhost
  roles:
    - fish
    - mise
