---
- hosts: localhost
  tasks:
    - name: Ensure Homebrew is up-to-date
      homebrew:
        update_homebrew: yes
        upgrade_all: yes
      when: not lookup("env", "CI")

    - name: Ensure Homebrew packages are installed
      homebrew:
        name:
          - asdf
          - bash
          - git
          - neovim
          - node
          - python
          - ruby
          - tmux
          - vim
          - zsh
