#!/bin/bash

if [ `uname` == "Darwin" ];
then
	alias ls="/bin/ls -FG";
else
	alias ls="/bin/ls -F --color";
fi;

# cdls
#	Change directory and list it
function cdls {
	if [ "$#" -eq "0" ];
	then
		cd "$HOME";
	else
		cd "$*";
	fi
	ls;
}

alias cd="cdls";

alias .="ls";
alias ..="cd ..";

#	mkcd
#	Make a directory and change the working directory
function mkcd {
	mkdir "$1";
	cd "$1";
}

# topen
# Touch a file and open it with default app
function topen {
	touch $1;
	open $1;
}

if [ `uname` == "Darwin" ];
then
	CORES=`/usr/sbin/system_profiler SPHardwareDataType | grep "Cores" | egrep -oe "[[:digit:]]+"`;
	alias make="make --no-print-directory -j $CORES";
else
	alias make="make --no-print-directory";
fi;
