#!/bin/bash

prompt_git() {
	git branch &>/dev/null || return 1
	HEAD="$(git symbolic-ref HEAD 2>/dev/null)"
	BRANCH="${HEAD##*/}"
	[[ -n "$(git status 2>/dev/null | \
		grep -F 'working directory clean')" ]] || STATUS="!"
	printf ' (%s)' "${BRANCH:-unknown}${STATUS}"
}

export PS1="\n$(prompt_git)  \w\n[\!] \u \$ ";
