#!/bin/bash

#echo "$@"

case "$1" in
di|di.uminho)
	export HTTP_PROXY="http://proxy.di.uminho.pt:3128";
	export HTTPS_PROXY="https://proxy.di.uminho.pt:3128";
	export FTP_PROXY="ftp://proxy.di.uminho.pt:3128";
	export SOCKS_PROXY="socks://socks.di.uminho.pt:1080";
	;;
uminho)
	export HTTP_PROXY="http://proxy.uminho.pt:3128";
	export HTTPS_PROXY="https://proxy.uminho.pt:3128";
	export FTP_PROXY="ftp://proxy.uminho.pt:3128";
	export SOCKS_PROXY="socks://socks.uminho.pt:1080";
	;;
*)
	unset HTTP_PROXY;
	unset HTTPS_PROXY;
	unset FTP_PROXY;
	unset SOCKS_PROXY;
	;;
esac
