#!/bin/bash

PAINT=mspaint

USE_COLOR=`which "$PAINT"`;

if [ "$USE_COLOR" ]; then
	setup_ps1 () {
		if [ "$?" == "0" ];
		then
			DELIM_COLOR="green";
		else
			DELIM_COLOR="red";
		fi;
		export PS1="\n\u$($PAINT -B -w @)\H:$($PAINT -f magenta -w "\\w")  [$(git-prompt)]\n $($PAINT -f $DELIM_COLOR -w "\\$") "

		# cleanup
		unset DELIM_COLOR;
	}
else
	setup_ps1 () {
		export PS1="\n\u@\H:\w  [$(git-prompt)]\n \$ ";
	}
fi;