#!/bin/bash

# git aliases
alias grh="git reset --hard HEAD";
alias ga="git add .";
gc () {
	if [ "$1" ];
	then
		git commit -a -m "$1";
	else
		git commit -a;
	fi;
}
alias gac="ga && gc";
alias gp="git push";
gacp () {
	if [ "$1" ];
	then
		gac "$1" && gp;
	else 
		gac && gp;
	fi;
}